=== commandus/wml/etc/taxon10.dtd
<!--
    Taxon Type Definition version 1.0.0

    Version:  1.0.1
    Revision: Nov 18 2003

    Authors:  Andrei Ivanov <support@commandus.com>
    Copyright &copy; Andrei Ivanov, 2003. All rights reserved.  

    Usage:
      <?xml version="1.0" encoding="utf-8"?>
      <!DOCTYPE taxon PUBLIC "-//taxon//DTD taxon 1.0//EN" "http://ensen.sitc.ru/dtds/taxon-1.0/taxon10.dtd">
      <taxon>
        ...
      </taxon>

    Terms and conditions of use are available from the web site at
      http://commandus.com/dtd/

-->
<!--================ Entities ================-->
<!ENTITY % id "CDATA">
<!-- [0-9A-z_]+ for identifier -->
<!ENTITY % length "CDATA">
<!-- [0-9]+ for absolute or [0-9]+"%" for percentage length -->
<!ENTITY % vdata "CDATA">
<!-- attribute value possibly containing variable references -->
<!ENTITY % href "%vdata;">
<!-- URI, URL or URN designating a hypertext node. May contain variable references -->
<!ENTITY % number "NMTOKEN">
<!-- a number, with format [0-9]+ -->
<!ENTITY % coreattrs "id    ID     #IMPLIED 
                       class CDATA  #IMPLIED">
<!ENTITY % sysname "(kingdom|subkingdom|division|subdivision|superclass|class|phylum|subphylum|infraclass|superorder|order|suborder|superfamily|family|subfamily|infrafamily|tribe|subtribe|genus|subgenus|section|species|taxon|outgroup)">
<!ENTITY % regiontype "(ocean|sea|basin)">
<!ENTITY % InternationalAttributes "xml:lang		%id;		#IMPLIED">
<!ENTITY % DCAttributes "id			%id;		#IMPLIED
  %InternationalAttributes;
  xmlns:dc		%href;		#FIXED 'http://purl.org/dc/elements/1.0/'">
<!ENTITY % nmtoken "CDATA">
<!-- [0-9A-z_]+ for identifier -->
<!--================ Taxon ================-->
<!ELEMENT taxon (comment*, ssScript*, sys+, title*, description*, synonyms?, authors?, distributions?, publications?, date?, plants?, symbiosises?, collections?, x-metadata?)>
<!ATTLIST taxon
	id %id; #IMPLIED
	%InternationalAttributes; 
	href %href; #IMPLIED
	unique-identifier %id; #IMPLIED
	xmlns:taxon %href; #FIXED "http://commandus.com/dtd/taxon/1.0/"
>
<!ELEMENT ssScript EMPTY>
<!ATTLIST ssScript
	value CDATA #IMPLIED
>
<!ELEMENT sys (comment*, ssScript*, text)>
<!ATTLIST sys
	%InternationalAttributes; 
	href %href; #IMPLIED
	name %sysname; #REQUIRED
	rank %number; #IMPLIED
>
<!ELEMENT text EMPTY>
<!ATTLIST text
	value CDATA #REQUIRED
>
<!ELEMENT title (comment*, ssScript*, text)>
<!ATTLIST title
	%InternationalAttributes; 
	option CDATA #IMPLIED
>
<!ELEMENT description (comment*, ssScript*, text?)>
<!ATTLIST description
	%InternationalAttributes; 
>
<!ELEMENT synonyms (comment*, ssScript*, name+)>
<!ELEMENT name (comment*, ssScript*, text)>
<!ATTLIST name
	%InternationalAttributes; 
	option CDATA #IMPLIED
>
<!ELEMENT authors (comment*, ssScript*, person+)>
<!ELEMENT person (comment*, ssScript*, name+, description*, degree*, position*, institute*, department*, phone*, mail*, email*, birthday?, dyingday?, x-metadata?)>
<!ATTLIST person
	href %href; #IMPLIED
	date %vdata; #IMPLIED
	rel %vdata; #IMPLIED
>
<!ELEMENT degree (comment*, ssScript*, text)>
<!ELEMENT position (comment*, ssScript*, text)>
<!ATTLIST position
	%InternationalAttributes; 
>
<!ELEMENT institute (comment*, ssScript*, text)>
<!ATTLIST institute
	%InternationalAttributes; 
>
<!ELEMENT department (comment*, ssScript*, text)>
<!ATTLIST department
	%InternationalAttributes; 
>
<!ELEMENT phone (comment*, ssScript*, text)>
<!ELEMENT mail (comment*, ssScript*, text)>
<!ATTLIST mail
	%InternationalAttributes; 
>
<!ELEMENT email (comment*, ssScript*, text)>
<!ELEMENT birthday (comment*, ssScript*, text)>
<!ELEMENT dyingday (comment*, ssScript*, text)>
<!ELEMENT x-metadata (comment*, ssScript*, meta+)>
<!ATTLIST x-metadata
	id %id; #IMPLIED
	%InternationalAttributes; 
>
<!ELEMENT meta (comment*, ssScript*)>
<!ATTLIST meta
	%InternationalAttributes; 
	name %nmtoken; #REQUIRED
	content CDATA #REQUIRED
	scheme CDATA #IMPLIED
>
<!ELEMENT distributions (comment*, ssScript*, distribution+)>
<!ELEMENT distribution (comment*, ssScript*, description*, area?, stay?, label?, authors?, publications?, x-metadata?)>
<!ATTLIST distribution
	unique-identifier %id; #IMPLIED
	href %href; #IMPLIED
>
<!ELEMENT area (comment*, ssScript*, description*, region?, territory?, location?, authors?, publications?, x-metadata?)>
<!ATTLIST area
	unique-identifier %id; #IMPLIED
	name %vdata; #IMPLIED
	href %href; #IMPLIED
>
<!ELEMENT region (comment*, ssScript*, text?, description*, authors?, publications?, x-metadata?)>
<!ATTLIST region
	%InternationalAttributes; 
	href %href; #IMPLIED
	type %regiontype; #IMPLIED
>
<!ELEMENT publications (comment*, ssScript*, publication+)>
<!ELEMENT publication (comment*, ssScript*, opf?, record?, description*, dc-metadata?, x-metadata?, authors*)>
<!ATTLIST publication
	href %href; #IMPLIED
	unique-identifier %id; #IMPLIED
>
<!ELEMENT opf (comment*, ssScript*)>
<!ATTLIST opf
	href %href; #IMPLIED
>
<!ELEMENT record (comment*, ssScript*, text)>
<!ATTLIST record
	%InternationalAttributes; 
	href %href; #IMPLIED
>
<!ELEMENT dc-metadata (comment*, ssScript*, text*, dc:Title, dc:Identifier, dc:Contributor?, dc:Creator?, dc:Subject?, dc:Description?, dc:Publisher?, dc:Date?, dc:Type?, dc:Format?, dc:Source?, dc:Language?, dc:Relation?, dc:Coverage?, dc:Rights?)>
<!ATTLIST dc-metadata
	id %id; #IMPLIED
	%InternationalAttributes; 
	xmlns:dc %href; #FIXED "http://purl.org/dc/elements/1.0/"
	xmlns:oebpackage %href; #FIXED "http://openebook.org/namespaces/oeb-package/1.0/"
>
<!ELEMENT dc:Title (comment*, ssScript*, text*)>
<!ATTLIST dc:Title
	%DCAttributes; 
>
<!ELEMENT dc:Identifier (comment*, ssScript*, text*)>
<!ATTLIST dc:Identifier
	%DCAttributes; 
	scheme (ISBN | DOI) #IMPLIED
>
<!ELEMENT dc:Contributor (comment*, ssScript*, text*)>
<!ATTLIST dc:Contributor
	%DCAttributes; 
	role (adp | ann | arr | art | asn | aut | aqt | aft | aui | ant | bkp | clb | cmm | com | dsr | edt | ill | lyr | mdc | mus | nrt | oth | pht | prt | red | rev | spn | ths | trc | trl) #IMPLIED
	file-as CDATA #IMPLIED
>
<!ELEMENT dc:Creator (comment*, ssScript*, text*)>
<!ATTLIST dc:Creator
	%DCAttributes; 
	role (adp | ann | arr | art | asn | aut | aqt | aft | aui | ant | bkp | clb | cmm | com | dsr | edt | ill | lyr | mdc | mus | nrt | oth | pht | prt | red | rev | spn | ths | trc | trl) #IMPLIED
	file-as CDATA #IMPLIED
>
<!ELEMENT dc:Subject (comment*, ssScript*, text*)>
<!ATTLIST dc:Subject
	%DCAttributes; 
>
<!ELEMENT dc:Description (comment*, ssScript*, text*)>
<!ATTLIST dc:Description
	%DCAttributes; 
>
<!ELEMENT dc:Publisher (comment*, ssScript*, text*)>
<!ATTLIST dc:Publisher
	%DCAttributes; 
>
<!ELEMENT dc:Date (comment*, ssScript*, text*)>
<!ATTLIST dc:Date
	%DCAttributes; 
	event (creation | publication | modification) #IMPLIED
>
<!ELEMENT dc:Type (comment*, ssScript*, text*)>
<!ATTLIST dc:Type
	%DCAttributes; 
>
<!ELEMENT dc:Format (comment*, ssScript*, text*)>
<!ATTLIST dc:Format
	%DCAttributes; 
>
<!ELEMENT dc:Source (comment*, ssScript*, text*)>
<!ATTLIST dc:Source
	%DCAttributes; 
>
<!ELEMENT dc:Language (comment*, ssScript*, text*)>
<!ATTLIST dc:Language
	%DCAttributes; 
>
<!ELEMENT dc:Relation (comment*, ssScript*, text*)>
<!ATTLIST dc:Relation
	%DCAttributes; 
>
<!ELEMENT dc:Coverage (comment*, ssScript*, text*)>
<!ATTLIST dc:Coverage
	%DCAttributes; 
>
<!ELEMENT dc:Rights (comment*, ssScript*, text*)>
<!ATTLIST dc:Rights
	%DCAttributes; 
>
<!ELEMENT territory (comment*, ssScript*, text?, description*, authors?, publications?, x-metadata?)>
<!ATTLIST territory
	%InternationalAttributes; 
	href %href; #IMPLIED
	type %regiontype; #IMPLIED
>
<!ELEMENT location (comment*, ssScript*, text?, description*, authors?, publications?, x-metadata?)>
<!ATTLIST location
	%InternationalAttributes; 
	href %href; #IMPLIED
	name %vdata; #IMPLIED
>
<!ELEMENT stay (comment*, ssScript*, description*, source?, location?, horisont?, section?, square?, depth?, date?, gear?, sample?, authors?, publications?, x-metadata?)>
<!ATTLIST stay
	unique-identifier %id; #IMPLIED
	href %href; #IMPLIED
	type (station | vessel) #IMPLIED
>
<!ELEMENT source (comment*, ssScript*, text?, description*, x-metadata?)>
<!ATTLIST source
	%InternationalAttributes; 
	href %href; #IMPLIED
	type (log) #IMPLIED
>
<!ELEMENT horisont (comment*, ssScript*, text?, description*, x-metadata?)>
<!ATTLIST horisont
	%InternationalAttributes; 
	href %href; #IMPLIED
	type (hydro | pelagy) #IMPLIED
>
<!ELEMENT section (comment*, ssScript*, text?, description*, x-metadata?)>
<!ATTLIST section
	%InternationalAttributes; 
	href %href; #IMPLIED
	type (hydro | pelagy) #IMPLIED
>
<!ELEMENT square (comment*, ssScript*, text?, description*, x-metadata?)>
<!ATTLIST square
	%InternationalAttributes; 
	href %href; #IMPLIED
	type (hydro | pelagy) #IMPLIED
>
<!ELEMENT depth (comment*, ssScript*)>
<!ATTLIST depth
	%InternationalAttributes; 
	value %length; #IMPLIED
	ratio %length; #IMPLIED
>
<!ELEMENT date (comment*, ssScript*)>
<!ATTLIST date
	value CDATA #IMPLIED
	ratio %length; #IMPLIED
>
<!ELEMENT gear (comment*, ssScript*)>
<!ATTLIST gear
	%InternationalAttributes; 
	value CDATA #IMPLIED
	alt CDATA #IMPLIED
>
<!ELEMENT sample (comment*, ssScript*)>
<!ATTLIST sample
	%InternationalAttributes; 
	value CDATA #IMPLIED
	alt CDATA #IMPLIED
>
<!ELEMENT label (comment*, ssScript*, description*, latitude?, longitude?, base?, point?, x-metadata?)>
<!ELEMENT latitude (comment*, ssScript*)>
<!ATTLIST latitude
	value CDATA #IMPLIED
	alt CDATA #IMPLIED
>
<!ELEMENT longitude (comment*, ssScript*)>
<!ATTLIST longitude
	value CDATA #IMPLIED
	alt CDATA #IMPLIED
>
<!ELEMENT base (comment*, ssScript*)>
<!ATTLIST base
	value CDATA #IMPLIED
	alt CDATA #IMPLIED
	distance %length; #IMPLIED
	direction (N | E | S | W) #IMPLIED
>
<!ELEMENT point (comment*, ssScript*)>
<!ATTLIST point
	%InternationalAttributes; 
	value CDATA #IMPLIED
	alt CDATA #IMPLIED
>
<!ELEMENT plants (comment*, ssScript*, symbiosis*)>
<!ELEMENT symbiosis (comment*, ssScript*, description*, taxon*, person*, publications*, region*, x-metadata?)>
<!ATTLIST symbiosis
	href %href; #IMPLIED
>
<!ELEMENT symbiosises (comment*, ssScript*, hosts?, parasites?, plants?)>
<!ELEMENT hosts (comment*, ssScript*, symbiosis*)>
<!ELEMENT parasites (comment*, ssScript*, symbiosis*)>
<!ELEMENT collections (comment*, ssScript*, collection+)>
<!ELEMENT collection (comment*, ssScript*, item*, x-metadata?)>
<!ATTLIST collection
	name CDATA #IMPLIED
>
<!ELEMENT item (comment*, ssScript*, sex?, age?, count?, date?, authors?, type?, distribution?, x-metadata?)>
<!ATTLIST item
	unique-identifier %id; #IMPLIED
>
<!ELEMENT sex (comment*, ssScript*)>
<!ATTLIST sex
	value (m | f) #IMPLIED
	ratio %length; #IMPLIED
>
<!ELEMENT age (comment*, ssScript*)>
<!ATTLIST age
	value %length; #IMPLIED
	ratio %length; #IMPLIED
>
<!ELEMENT count (comment*, ssScript*)>
<!ATTLIST count
	value %length; #IMPLIED
	ratio %length; #IMPLIED
>
<!ELEMENT type (comment*, ssScript*)>
<!ATTLIST type
	%InternationalAttributes; 
	value CDATA #IMPLIED
>

=== commandus/wml/etc/0112.txn.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE taxon PUBLIC "-//taxon//DTD taxon 1.0//EN" "file://e:\src\wml\etc\taxon10.dtd">
<taxon xml:ns="taxon">
  <sys name="Семейство" rank="1">
    Culicidae
  </sys>
  <sys name="Триба" rank="3">
    Aedini
  </sys>
  <sys name="Род" rank="4">
    Aedes
  </sys>
  <sys name="Подрод" rank="7">
    Aedes
  </sys>
  <sys name="Вид" rank="10">
    Aedes (Aedes) cinereus
  </sys>
  <authors>
    <person date="1818" rel="dsc-genus">
      <name>
        Meigen
      </name>
      <description>
        Описатель рода
      </description>
    </person>
    <person date="1818" rel="dsc-subgenus">
      <name>
        Meigen
      </name>
      <description>
        Описатель подрода
      </description>
    </person>
    <person date="1818" rel="dsc-species">
      <name>
        Meigen
      </name>
      <description>
        Описатель вида
      </description>
    </person>
  </authors>
  <date value="1818" ratio="1">
  </date>
  <synonyms>
    <name xml:lang="ru" option="Sakha">
      (rufus Gimmerthal, 1845, pseudoesoensis Yamaguti et Tamaboko, 1954)
    </name>
  </synonyms>
  <distributions>
    <distribution>
      <area>
        <description>
          Голаркт
        </description>
        <location xml:lang="ru">
          Голаркт
        </location>
      </area>
    </distribution>
    <distribution>
      <area name="Sakha">
        <location xml:lang="ru">
          ЗЯ:Нюрба, ЦЯ:Аллах, Еланское, Ерт, Кептин, Магарас, Мегино-Алдан, 
          Михайловка, Хаптагай, Якутск, ЮЗЯ: Токко, ЮЯ: Нерюнгри, Томмот, Чульман, 
          Ыллымах, Якокит
        </location>
      </area>
    </distribution>
    <distribution>
      <area name="Russia">
        <location xml:lang="ru">
          Сиб., ДВ, Чук., Маг., Камч., Хаб., Амур., Прим., Сах., Якут., Чит., 
          Бур., Иркут.
        </location>
      </area>
    </distribution>
    <distribution>
      <area name="Earth">
        <location xml:lang="ru">
          Умеренная полоса Евразии и С Америки - Европа, Канада, С США, СВ 
          Китай, Япония, Кавказ, Ср. Азия, Каз.,
        </location>
      </area>
    </distribution>
  </distributions>
</taxon>
